# Generated by Django 5.0.2 on 2024-02-14 17:10

import forms_first_excercise.model_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=35, validators=[forms_first_excercise.model_form.models.non_empty]),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=35, validators=[forms_first_excercise.model_form.models.non_empty]),
        ),
    ]
