# Generated by Django 5.0.3 on 2024-03-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
