# Generated by Django 5.0.2 on 2024-03-03 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_clothes', '0002_orderclothes_category_orderclothes_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclothes',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
