# Generated by Django 5.0.2 on 2024-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_clothes', '0004_alter_orderclothes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclothes',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
