# Generated by Django 5.0.2 on 2024-03-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_clothes', '0005_alter_orderclothes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclothes',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
