# Generated by Django 5.0.2 on 2024-03-04 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_clothes', '0006_orderclothes_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclothes',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
