# Generated by Django 5.0.2 on 2024-03-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_clothes', '0007_orderclothes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclothes',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
