# Generated by Django 5.0.2 on 2024-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModelCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('size', models.CharField(choices=[('1/43', '1/43'), ('1/24', '1/24'), ('1/18', '1/18')], max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
