# Generated by Django 5.0.2 on 2024-02-21 14:32

import django.core.validators
import exam_prep_one.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), exam_prep_one.profiles.models.validate_username]),
        ),
    ]
