# Generated by Django 5.0.2 on 2024-02-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], null=True),
        ),
    ]
