# Generated by Django 5.0.2 on 2024-02-16 17:32

import django.core.validators
import forms_advanced.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2), forms_advanced.web.models.validate_first_name]),
        ),
    ]
