# Generated by Django 5.0.2 on 2024-02-16 18:44

import django.core.validators
import forms_advanced.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_person_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='asd', max_length=32, validators=[django.core.validators.MinLengthValidator(2), forms_advanced.web.models.validate_first_name]),
            preserve_default=False,
        ),
    ]
