# Generated by Django 5.0.2 on 2024-03-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
