# Generated by Django 5.0.2 on 2024-03-04 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_alter_shoppingcart_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
