# Generated by Django 5.0.2 on 2024-03-04 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_clothes', '0008_orderclothes_quantity'),
        ('shopping_cart', '0006_remove_orderitem_item_orderitem_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='merch_clothes.orderclothes'),
            preserve_default=False,
        ),
    ]
